-- Seed sample jobs for testing
INSERT INTO public.jobs (title, company, company_logo, location, location_type, employment_type, salary_min, salary_max, description, requirements, benefits, category, experience_level, requires_screening) VALUES
('Senior Full Stack Engineer', 'TechCorp', '/placeholder.svg?height=80&width=80', 'San Francisco, CA', 'hybrid', 'full-time', 150000, 200000, 'Join our team to build scalable web applications using modern technologies. You will work on challenging problems and collaborate with talented engineers.', ARRAY['5+ years of experience', 'React, Node.js, TypeScript', 'System design expertise', 'Strong communication skills'], ARRAY['Health insurance', 'Stock options', 'Unlimited PTO', '401k matching'], 'Engineering', 'senior', true),

('Product Designer', 'DesignHub', '/placeholder.svg?height=80&width=80', 'New York, NY', 'remote', 'full-time', 100000, 140000, 'Create beautiful and intuitive user experiences for our SaaS platform. Work closely with product and engineering teams.', ARRAY['3+ years of product design', 'Figma expertise', 'User research experience', 'Portfolio required'], ARRAY['Remote work', 'Health insurance', 'Learning budget', 'Home office stipend'], 'Design', 'mid', false),

('Marketing Manager', 'GrowthLabs', '/placeholder.svg?height=80&width=80', 'Austin, TX', 'onsite', 'full-time', 90000, 120000, 'Lead our marketing initiatives and drive growth through data-driven campaigns. Manage a small team and work with leadership.', ARRAY['5+ years marketing experience', 'B2B SaaS background', 'Team management', 'Analytics proficiency'], ARRAY['Health insurance', 'Bonus structure', 'Professional development', 'Gym membership'], 'Marketing', 'senior', true),

('Junior Software Engineer', 'StartupXYZ', '/placeholder.svg?height=80&width=80', 'Remote', 'remote', 'full-time', 70000, 90000, 'Perfect for new grads or career changers. Learn from experienced engineers while building real products.', ARRAY['CS degree or bootcamp', 'JavaScript/Python basics', 'Eagerness to learn', 'Problem-solving skills'], ARRAY['Remote work', 'Mentorship program', 'Health insurance', 'Equity'], 'Engineering', 'entry', false),

('Data Scientist', 'DataCo', '/placeholder.svg?height=80&width=80', 'Seattle, WA', 'hybrid', 'full-time', 130000, 170000, 'Build ML models and analyze large datasets to drive business decisions. Work with cutting-edge AI technologies.', ARRAY['PhD or Masters in related field', 'Python, SQL, ML frameworks', 'Statistical analysis', 'Communication skills'], ARRAY['Health insurance', 'Stock options', 'Conference budget', 'Flexible hours'], 'Data Science', 'senior', true),

('DevOps Engineer', 'CloudTech', '/placeholder.svg?height=80&width=80', 'Boston, MA', 'remote', 'full-time', 120000, 160000, 'Manage our cloud infrastructure and CI/CD pipelines. Ensure reliability and scalability of our systems.', ARRAY['4+ years DevOps experience', 'AWS/GCP/Azure', 'Kubernetes, Docker', 'Infrastructure as code'], ARRAY['Remote work', 'Health insurance', 'Learning budget', 'Stock options'], 'Engineering', 'mid', false),

('Content Writer', 'MediaHub', '/placeholder.svg?height=80&width=80', 'Los Angeles, CA', 'remote', 'contract', 50000, 70000, 'Create engaging content for our blog and marketing materials. Research and write about tech trends.', ARRAY['2+ years writing experience', 'Tech industry knowledge', 'SEO understanding', 'Portfolio required'], ARRAY['Remote work', 'Flexible schedule', 'Byline credit', 'Networking opportunities'], 'Content', 'entry', false),

('Sales Executive', 'SalesPro', '/placeholder.svg?height=80&width=80', 'Chicago, IL', 'hybrid', 'full-time', 80000, 150000, 'Drive revenue by closing enterprise deals. Build relationships with key decision makers.', ARRAY['5+ years B2B sales', 'Enterprise sales experience', 'CRM proficiency', 'Strong negotiation skills'], ARRAY['Uncapped commission', 'Health insurance', 'Car allowance', 'President''s club'], 'Sales', 'senior', true);
